# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise32"
  #config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network :forwarded_port, host: 4567, guest: 80
  #config.vm.network :forwarded_port, host: 873, guest: 80

  config.vm.provision :shell do |s|
    s.inline = "apt-get update"
    #s.inline = "apt-get upgrade -y"
    s.inline = "apt-get -y install xinetd"
  end


  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "networking_basic"
    chef.add_recipe "xinitd_rsync"
    chef.node_name = "rsync-aws"
  end

end
